project_id = "udeslpcxefsjtvefqcqh"

[functions.export-data]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.client-portal-upload]
verify_jwt = false

[functions.client-portal-file-url]
verify_jwt = false

