
ALTER TABLE public.orders
  ADD COLUMN IF NOT EXISTS total_revenue NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_cost NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS amount_received NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS amount_pending NUMERIC NOT NULL DEFAULT 0;
